# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        # ROLE_ADMIN:       ROLE_USER
        # ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_VENTA_A: ROLE_VENTA_B
        ROLE_ADMIN_D: ROLE_VENTA_A
        ROLE_ADMIN_C: ROLE_ADMIN_D
        ROLE_ADMIN_B: ROLE_ADMIN_C
        ROLE_ADMIN_A: ROLE_ADMIN_B
        ROLE_SUPER_ADMIN: ROLE_ADMIN_A

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /admin # mia
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            anonymous:    true
            logout:
                target: /login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_FULLY } #ROLE_ADMIN